[package]
name = "library"
version = "0.0.1" 
description = "library for unsafe_features_example"
authors = ["Luciano Bestia"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucianobestia/unsafe_features_example"
categories = [""]
keywords = [""]
publish = false

[features]
unsafe_feature_read_private_key = []
# optional dependency for fs: unsafe_feature_read_private_key = [std_fs]
unsafe_feature_read_song = []
# optional dependency for fs: unsafe_feature_read_song = [std_fs]

[dependencies]
cfg-if="0.1.10"
# std_fs should be opt-in. It is clear that if this dependecy is used than the crate want file access.
# std_fs = { optional = true }
# there could be also other crates that allow file access. They should have an unsafe_feature with optional dependency clearly stated.
